#!/usr/bin/env bash
# lib/setup-local.sh — First-run prompts and generate git/ssh local configs from dotfiles.local.env

_setup_marker() {
  echo "${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles/.setup-done"
}

_env_file() { echo "${DOTFILES:-$HOME/.dotfiles}/dotfiles.local.env"; }
_env_example() { echo "${DOTFILES:-$HOME/.dotfiles}/dotfiles.local.env.example"; }

# Keys to prompt (order matters). Optional keys allow empty input.
_SETUP_KEYS=(
  DOTFILES_GITDIR_PERSONAL
  DOTFILES_GITDIR_UPTIME
  DOTFILES_GITHUB_ROOT
  DOTFILES_SSH_SERVER_IP
  DOTFILES_SSH_KEY_KVM
  DOTFILES_EDITOR_HOSTNAME
)

_setup_default_for_key() {
  local key="$1"
  local line
  line="$(grep -E "^${key}=" "$(_env_example)" 2>/dev/null | head -1)" || return 0
  line="${line#*=}"
  # Strip surrounding quotes
  line="${line%\"}"
  line="${line#\"}"
  line="${line%\'}"
  line="${line#\'}"
  eval "printf '%s' $line"
}

_setup_prompt_env() {
  log_section "First-run setup (dotfiles.local.env)"
  log_info "Press Enter to accept the default shown in [brackets]."

  local key default input
  local -a lines=()

  lines+=("# Generated by dotfiles install on $(date -Iseconds)")
  lines+=("# Edit dotfiles.local.env and re-run: ./install.sh --setup-only")

  for key in "${_SETUP_KEYS[@]}"; do
    default="$(_setup_default_for_key "$key")"
    if [[ "$key" == "DOTFILES_EDITOR_HOSTNAME" ]]; then
      read -rp "$key [${default:-empty}]: " input
      input="${input:-$default}"
    else
      read -rp "$key [${default}]: " input
      input="${input:-$default}"
    fi
    # Escape double quotes in values
    input="${input//\"/\\\"}"
    lines+=("${key}=\"${input}\"")
  done

  if [[ "$DRY_RUN" == "true" ]]; then
    log_dry "write $(_env_file) (${#lines[@]} lines)"
    return 0
  fi

  printf '%s\n' "${lines[@]}" >"$(_env_file)"
  chmod 600 "$(_env_file)"
  log_ok "Wrote $(_env_file)"
}

_setup_load_env() {
  if [[ -f "$(_env_file)" ]]; then
    set -a
    # shellcheck source=/dev/null
    source "$(_env_file)"
    set +a
  fi
}

_setup_generate_gitconfig_local() {
  local out="$DOTFILES/git/gitconfig-local"
  local personal="${DOTFILES_GITDIR_PERSONAL:-}"
  local uptime="${DOTFILES_GITDIR_UPTIME:-}"

  if [[ "$DRY_RUN" == "true" ]]; then
    log_dry "generate $out"
    return 0
  fi

  cat >"$out" <<EOF
# Generated from dotfiles.local.env — do not edit by hand (re-run --setup-only)
EOF

  if [[ -n "$personal" ]]; then
    cat >>"$out" <<EOF

[includeIf "gitdir:${personal}/"]
    path = gitconfig-personal
[includeIf "gitdir:${personal}/**"]
    path = gitconfig-personal
EOF
  fi

  if [[ -n "$uptime" ]]; then
    cat >>"$out" <<EOF

[includeIf "gitdir:${uptime}/"]
    path = gitconfig-uptime
[includeIf "gitdir:${uptime}/**"]
    path = gitconfig-uptime
EOF
  fi

  log_ok "Generated $out"
}

_setup_generate_ssh_config_local() {
  local out="$DOTFILES/ssh/config.local"
  local ip="${DOTFILES_SSH_SERVER_IP:-}"
  local key_kvm="${DOTFILES_SSH_KEY_KVM:-}"

  if [[ "$DRY_RUN" == "true" ]]; then
    log_dry "generate $out"
    return 0
  fi

  cat >"$out" <<'EOF'
# Generated from dotfiles.local.env — do not edit by hand (re-run --setup-only)
EOF

  if [[ -n "$ip" && -n "$key_kvm" ]]; then
    cat >>"$out" <<EOF

Host dotfiles-kvm-root
  HostName ${ip}
  User root
  IdentityFile ${key_kvm}

Host dotfiles-kvm-snsm
  HostName ${ip}
  User snsm
  IdentityFile ${key_kvm}
EOF
  fi

  chmod 600 "$out"
  log_ok "Generated $out"
}

_setup_link_gitconfig_local() {
  local src="$DOTFILES/git/gitconfig-local"
  local tgt="$XDG_CONFIG_HOME/git/gitconfig-local"
  [[ -f "$src" ]] || return 0
  link "$src" "$tgt"
}

_setup_mark_done() {
  local marker
  marker="$(_setup_marker)"
  if [[ "$DRY_RUN" == "true" ]]; then
    log_dry "touch $marker"
    return 0
  fi
  mkdir -p "$(dirname "$marker")"
  touch "$marker"
  log_ok "Setup complete ($marker)"
}

# run_setup_local [interactive|regenerate]
#   interactive — prompt if marker missing
#   regenerate  — load env and regenerate only
run_setup_local() {
  local mode="${1:-interactive}"

  [[ -f "$(_env_example)" ]] || {
    log_error "Missing $(_env_example)"
    exit 1
  }

  case "$mode" in
  interactive)
    if [[ -f "$(_setup_marker)" ]]; then
      log_skip "First-run setup already done ($(_setup_marker))"
      _setup_load_env
      return 0
    fi
    _setup_prompt_env
    _setup_load_env
    _setup_generate_gitconfig_local
    _setup_generate_ssh_config_local
    _setup_link_gitconfig_local
    _setup_mark_done
    ;;
  regenerate)
    _setup_load_env
    _setup_generate_gitconfig_local
    _setup_generate_ssh_config_local
    _setup_link_gitconfig_local
    log_ok "Regenerated local configs from $(_env_file)"
    ;;
  *)
    log_error "run_setup_local: unknown mode $mode"
    exit 1
    ;;
  esac
}
