#################
#    PLUGINS    #
#################

set-environment -g TMUX_PLUGIN_MANAGER_PATH "$XDG_DATA_HOME/tmux/plugins"

# Plugins
set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'wfxr/tmux-fzf-url'

#################
# SANE DEFAULTS #
#################

# Set the default terminal
set -g default-terminal "screen-256color"

# Fix backspace key and support true color
set -g terminal-overrides ',xterm*:smcup@:rmcup@:Tc'

# Vi mode
# set-window-option -g mode-keys vi
set -g mouse on

# Quick edit tmux
bind-key R source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# Panes in the same path
unbind c
bind c new-window -c '#{pane_current_path}'
unbind %
bind % split-window -h -c '#{pane_current_path}'
unbind '"'
bind '"' split-window -v -c '#{pane_current_path}'

# Default home and end
bind -n End send-key C-e
bind -n Home send-key C-a

# Vim-like key bindings for pane navigation (default uses cursor keys).
unbind h
bind h select-pane -L
unbind j
bind j select-pane -D
unbind k
bind k select-pane -U
unbind l # normally used for last-window
bind l select-pane -R

# Resizing (mouse also works).
unbind Left
bind -r Left resize-pane -L 5
unbind Right
bind -r Right resize-pane -R 5
unbind Down
bind -r Down resize-pane -D 5
unbind Up
bind -r Up resize-pane -U 5

# Fast toggle (normally prefix-l).
bind ^space last-window

# Intuitive window-splitting keys.
bind / split-window -h -c '#{pane_current_path}' # normally prefix-%
bind - split-window -v -c '#{pane_current_path}' # normally prefix-"

# Don't rename windows automatically
set-option -g allow-rename off

# History limit
set -g history-limit 10000

# Turn on window titles
set -g set-titles on

# Set wm window title string
set -g set-titles-string '#W'

# Automatically set window title
setw -g automatic-rename on

#################
# GRUVBOX THEME #
#################
set -g @tmux-gruvbox 'dark' # or 'light'

#################
#   RESURRECT   #
#################
set -g @resurrect-dir '~/.config/tmux/resurrect'

############
#  WINDOW  #
############

# Define key bindings for layout switching using Ctrl + b followed by Ctrl + <number>
bind S-1 select-layout even-horizontal
bind S-2 select-layout even-vertical
bind S-3 select-layout main-horizontal
bind S-4 select-layout main-vertical
bind S-5 select-layout tiled

# Bind Ctrl + B followed by M to move the current window to a specified number
bind M command-prompt -p "Move window to:" "move-window -t %%"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '$XDG_DATA_HOME/tmux/plugins/tpm/tpm'
